/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountHistoryModal: typeof import('./src/components/AccountHistoryModal.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    CartSidebar: typeof import('./src/components/CartSidebar.vue')['default']
    CatalogProductCard: typeof import('./src/components/CatalogProductCard.vue')['default']
    CatalogueCard: typeof import('./src/components/CatalogueCard.vue')['default']
    CatalogueView: typeof import('./src/components/CatalogueView.vue')['default']
    CategoryTabs: typeof import('./src/components/CategoryTabs.vue')['default']
    CheckoutModal: typeof import('./src/components/CheckoutModal.vue')['default']
    CreateLayawayModal: typeof import('./src/components/CreateLayawayModal.vue')['default']
    CustomerSelector: typeof import('./src/components/CustomerSelector.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    FilterSidebar: typeof import('./src/components/FilterSidebar.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    JewelryProductCard: typeof import('./src/components/JewelryProductCard.vue')['default']
    LayawayDetailModal: typeof import('./src/components/LayawayDetailModal.vue')['default']
    LayawayPaymentModal: typeof import('./src/components/LayawayPaymentModal.vue')['default']
    LiveGoldPrice: typeof import('./src/components/LiveGoldPrice.vue')['default']
    PortalLayout: typeof import('./src/components/PortalLayout.vue')['default']
    POSCatalog: typeof import('./src/components/POSCatalog.vue')['default']
    POSCategoryItems: typeof import('./src/components/POSCategoryItems.vue')['default']
    POSProductModal: typeof import('./src/components/POSProductModal.vue')['default']
    POSProfileSelector: typeof import('./src/components/POSProfileSelector.vue')['default']
    PreferencesModal: typeof import('./src/components/PreferencesModal.vue')['default']
    ProductModal: typeof import('./src/components/ProductModal.vue')['default']
    ProfileSettingsModal: typeof import('./src/components/ProfileSettingsModal.vue')['default']
    PromoBanner: typeof import('./src/components/PromoBanner.vue')['default']
    QuickLayawayModal: typeof import('./src/components/QuickLayawayModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportModal: typeof import('./src/components/SupportModal.vue')['default']
    TransactionDetailModal: typeof import('./src/components/TransactionDetailModal.vue')['default']
    TrendingSection: typeof import('./src/components/TrendingSection.vue')['default']
  }
}
