"""
Default shortcut definitions for Zevar Desk and Workspace.
"""

from __future__ import annotations


def get_default_shortcuts() -> list[dict]:
	"""Return the default shortcut registry used for bootstrap and migration."""
	pos_roles = ["Sales User", "POS Manager", "Store Manager", "System Manager"]
	crm_roles = ["Sales User", "Sales Manager", "System Manager"]
	customer_roles = ["Sales User", "Store Manager", "Accounts Manager", "System Manager"]
	source_roles = ["Purchase User", "Stock Manager", "Store Manager", "System Manager"]
	report_roles = ["Sales User", "Sales Manager", "Store Manager", "Accounts Manager", "System Manager"]
	inventory_roles = ["Stock Manager", "Store Manager", "System Manager"]
	time_clock_roles = ["Employee", "HR Manager", "System Manager"]
	admin_roles = ["System Manager"]

	return [
		{
			"shortcut_name": "POS",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos",
			"icon_name": "shopping-cart",
			"color": "#2563eb",
			"description": "Point of Sale terminal.",
			"sequence": 5,
			"keyboard_shortcut": "alt+p",
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Employee Portal",
			"section_name": "Time Clock",
			"link_type": "URL",
			"link_to": "/employee-portal",
			"icon_name": "user",
			"color": "#6b7280",
			"description": "Open the employee dashboard and portal.",
			"sequence": 6,
			"keyboard_shortcut": "alt+e",
			"roles": time_clock_roles,
		},
		{
			"shortcut_name": "CRM",
			"section_name": "CRM",
			"link_type": "URL",
			"link_to": "/crm",
			"icon_name": "users",
			"color": "#7c3aed",
			"description": "Manage leads, deals, and customer relationships.",
			"sequence": 7,
			"keyboard_shortcut": "alt+c",
			"roles": crm_roles,
		},
		{
			"shortcut_name": "CRM Leads",
			"section_name": "CRM",
			"link_type": "DocType",
			"link_to": "CRM Lead",
			"icon_name": "user",
			"color": "#2563eb",
			"description": "View and manage sales leads.",
			"sequence": 8,
			"roles": crm_roles,
		},
		{
			"shortcut_name": "CRM Deals",
			"section_name": "CRM",
			"link_type": "DocType",
			"link_to": "CRM Deal",
			"icon_name": "bar-chart-2",
			"color": "#059669",
			"description": "Track deal pipeline and closures.",
			"sequence": 9,
			"roles": crm_roles,
		},
		{
			"shortcut_name": "Sale / Return",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos",
			"icon_name": "shopping-cart",
			"color": "#2563eb",
			"description": "Open the POS terminal for sales and returns.",
			"sequence": 10,
			"keyboard_shortcut": "alt+p",
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Restore Transactions",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos/transactions",
			"icon_name": "repeat",
			"color": "#0f766e",
			"description": "Review recent POS transactions and recover interrupted work.",
			"sequence": 20,
			"roles": pos_roles,
		},
		{
			"shortcut_name": "View Transactions",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos/transactions",
			"icon_name": "file-text",
			"color": "#4f46e5",
			"description": "View and filter POS transaction history.",
			"sequence": 30,
			"keyboard_shortcut": "alt+v",
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Send File",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "File",
			"icon_name": "upload",
			"color": "#7c3aed",
			"description": "Open the file manager to share or upload exported files.",
			"sequence": 40,
			"roles": pos_roles,
		},
		{
			"shortcut_name": "New Layaway",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos/layaway",
			"icon_name": "plus",
			"color": "#8b5cf6",
			"description": "Create a new layaway contract from the POS terminal.",
			"sequence": 50,
			"keyboard_shortcut": "alt+l",
			"roles": pos_roles,
		},
		{
			"shortcut_name": "LA Payment",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos/layaway",
			"icon_name": "dollar-sign",
			"color": "#0891b2",
			"description": "Open the layaway screen to take a payment.",
			"sequence": 60,
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Edit Layaway",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos/layaway",
			"icon_name": "edit",
			"color": "#ea580c",
			"description": "Review and update an existing layaway contract.",
			"sequence": 70,
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Cancel Layaway",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos/layaway",
			"icon_name": "x",
			"color": "#dc2626",
			"description": "Open layaway management to cancel a contract when needed.",
			"sequence": 80,
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Appraisals",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Jewelry Appraisal",
			"icon_name": "gem",
			"color": "#d97706",
			"description": "Create and manage jewelry appraisals.",
			"sequence": 90,
			"keyboard_shortcut": "alt+a",
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Watch Purchases",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Purchase Order",
			"icon_name": "package",
			"color": "#0284c7",
			"description": "Track and enter watch purchase orders.",
			"sequence": 100,
			"roles": source_roles,
		},
		{
			"shortcut_name": "New A/R",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Customer Ledger Entry",
			"icon_name": "plus",
			"color": "#059669",
			"description": "Open customer ledger entries for new receivables.",
			"sequence": 110,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Installment Sale",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "In House Finance Account",
			"icon_name": "credit-card",
			"color": "#0f766e",
			"description": "Manage in-house installment sale accounts.",
			"sequence": 120,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "A/R Payment",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Payment Entry",
			"icon_name": "dollar-sign",
			"color": "#16a34a",
			"description": "Record an accounts receivable payment.",
			"sequence": 130,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Installment Payment",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Payment Entry",
			"icon_name": "check",
			"color": "#65a30d",
			"description": "Record installment payments against active finance accounts.",
			"sequence": 140,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "View S/O",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Sales Order",
			"icon_name": "clipboard-list",
			"color": "#2563eb",
			"description": "View submitted and draft sales orders.",
			"sequence": 150,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Special Order",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/app/sales-order/new-sales-order-1",
			"icon_name": "star",
			"color": "#c2410c",
			"description": "Create a new special order.",
			"sequence": 160,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Convert A/R",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Customer Ledger Entry",
			"icon_name": "repeat",
			"color": "#7c3aed",
			"description": "Review customer ledger entries for receivable conversion workflows.",
			"sequence": 170,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Paid Ins / Outs",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Payment Entry",
			"icon_name": "arrow-right",
			"color": "#0ea5e9",
			"description": "Open payment entries for paid in and paid out transactions.",
			"sequence": 180,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Repairs",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/pos/repairs",
			"icon_name": "tools",
			"color": "#f59e0b",
			"description": "Manage repair intake, status, and delivery.",
			"sequence": 190,
			"keyboard_shortcut": "alt+r",
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Repair Deposit",
			"section_name": "POS",
			"link_type": "DocType",
			"link_to": "Repair Order",
			"icon_name": "dollar-sign",
			"color": "#b45309",
			"description": "Open repair orders to manage repair deposits.",
			"sequence": 200,
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Exit",
			"section_name": "POS",
			"link_type": "URL",
			"link_to": "/zevar-desk",
			"icon_name": "home",
			"color": "#334155",
			"description": "Return to the Zevar custom desk.",
			"sequence": 210,
			"roles": pos_roles,
		},
		{
			"shortcut_name": "Customer List",
			"section_name": "Customer List",
			"link_type": "DocType",
			"link_to": "Customer",
			"icon_name": "users",
			"color": "#2563eb",
			"description": "Open the customer master list.",
			"sequence": 310,
			"keyboard_shortcut": "alt+c",
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Customer Ledger",
			"section_name": "Customer List",
			"link_type": "DocType",
			"link_to": "Customer Ledger Entry",
			"icon_name": "file-text",
			"color": "#4f46e5",
			"description": "Review customer ledger activity and balances.",
			"sequence": 320,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Trade-Ins",
			"section_name": "Customer List",
			"link_type": "DocType",
			"link_to": "Trade In Record",
			"icon_name": "repeat",
			"color": "#0f766e",
			"description": "Manage customer trade-in records.",
			"sequence": 330,
			"roles": customer_roles,
		},
		{
			"shortcut_name": "Source Management",
			"section_name": "Source Management",
			"link_type": "DocType",
			"link_to": "Supplier",
			"icon_name": "store",
			"color": "#1d4ed8",
			"description": "Manage supplier and source records.",
			"sequence": 410,
			"roles": source_roles,
		},
		{
			"shortcut_name": "Purchase Orders",
			"section_name": "Source Management",
			"link_type": "DocType",
			"link_to": "Purchase Order",
			"icon_name": "clipboard-list",
			"color": "#0891b2",
			"description": "Track inventory sourcing through purchase orders.",
			"sequence": 420,
			"roles": source_roles,
		},
		{
			"shortcut_name": "Purchase Invoices",
			"section_name": "Source Management",
			"link_type": "DocType",
			"link_to": "Purchase Invoice",
			"icon_name": "file-text",
			"color": "#0f766e",
			"description": "Open purchase invoices for source reconciliation.",
			"sequence": 430,
			"roles": source_roles,
		},
		{
			"shortcut_name": "Store Locations",
			"section_name": "Source Management",
			"link_type": "DocType",
			"link_to": "Store Location",
			"icon_name": "map-pin",
			"color": "#9333ea",
			"description": "Manage stores and sourcing locations.",
			"sequence": 440,
			"roles": source_roles,
		},
		{
			"shortcut_name": "Hourly Sales",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Hourly Sales",
			"icon_name": "bar-chart-2",
			"color": "#2563eb",
			"description": "Analyze hourly POS sales performance.",
			"sequence": 510,
			"roles": report_roles,
		},
		{
			"shortcut_name": "EOD Calendar",
			"section_name": "Reports",
			"link_type": "Page",
			"link_to": "eod-calendar",
			"icon_name": "calendar",
			"color": "#0ea5e9",
			"description": "View interactive daily analytics and YoY heatmap.",
			"sequence": 515,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Payment Summary",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Payment Method Summary",
			"icon_name": "dollar-sign",
			"color": "#16a34a",
			"description": "Summarize sales by payment method.",
			"sequence": 520,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Layaway Status",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Layaway Status",
			"icon_name": "credit-card",
			"color": "#7c3aed",
			"description": "Review active and completed layaway contracts.",
			"sequence": 530,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Layaway Aging",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Layaway Aging",
			"icon_name": "calendar",
			"color": "#0f766e",
			"description": "See overdue and aging layaway balances.",
			"sequence": 540,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Commission Summary",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Commission Summary",
			"icon_name": "percentage",
			"color": "#ea580c",
			"description": "View summarized commission performance.",
			"sequence": 550,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Gold Rate History",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Gold Rate History",
			"icon_name": "dollar-sign",
			"color": "#ca8a04",
			"description": "Track historical precious metal rates.",
			"sequence": 560,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Low Stock Alert",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Low Stock Alert",
			"icon_name": "alert-circle",
			"color": "#dc2626",
			"description": "Identify items that need replenishment.",
			"sequence": 570,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Trade-In Summary",
			"section_name": "Reports",
			"link_type": "Report",
			"link_to": "Trade-In Summary",
			"icon_name": "repeat",
			"color": "#0284c7",
			"description": "Summarize trade-in activity.",
			"sequence": 580,
			"roles": report_roles,
		},
		{
			"shortcut_name": "Inventory",
			"section_name": "Inventory",
			"link_type": "DocType",
			"link_to": "Item",
			"icon_name": "package",
			"color": "#2563eb",
			"description": "Open the main inventory item list.",
			"sequence": 610,
			"keyboard_shortcut": "alt+i",
			"roles": inventory_roles,
		},
		{
			"shortcut_name": "Stock Entry",
			"section_name": "Inventory",
			"link_type": "DocType",
			"link_to": "Stock Entry",
			"icon_name": "arrow-right",
			"color": "#059669",
			"description": "Create and review stock movements.",
			"sequence": 620,
			"roles": inventory_roles,
		},
		{
			"shortcut_name": "Serial Numbers",
			"section_name": "Inventory",
			"link_type": "DocType",
			"link_to": "Serial No",
			"icon_name": "bookmark",
			"color": "#7c3aed",
			"description": "Look up serial-tracked inventory.",
			"sequence": 630,
			"roles": inventory_roles,
		},
		{
			"shortcut_name": "Catalogues",
			"section_name": "Inventory",
			"link_type": "URL",
			"link_to": "/catalogues",
			"icon_name": "image",
			"color": "#0891b2",
			"description": "Browse the visual product catalogue.",
			"sequence": 640,
			"roles": inventory_roles,
		},
		{
			"shortcut_name": "Gold Rate Log",
			"section_name": "Inventory",
			"link_type": "DocType",
			"link_to": "Gold Rate Log",
			"icon_name": "dollar-sign",
			"color": "#ca8a04",
			"description": "Review current gold rate entries.",
			"sequence": 650,
			"roles": inventory_roles,
		},
		{
			"shortcut_name": "Time Clock",
			"section_name": "Time Clock",
			"link_type": "URL",
			"link_to": "/employee-portal#/",
			"icon_name": "home",
			"color": "#2563eb",
			"description": "Open the employee dashboard and time clock.",
			"sequence": 710,
			"keyboard_shortcut": "alt+t",
			"roles": time_clock_roles,
		},
		{
			"shortcut_name": "Attendance",
			"section_name": "Time Clock",
			"link_type": "URL",
			"link_to": "/employee-portal#/attendance",
			"icon_name": "calendar",
			"color": "#0f766e",
			"description": "Go directly to attendance history and clock actions.",
			"sequence": 720,
			"roles": time_clock_roles,
		},
		{
			"shortcut_name": "Roster",
			"section_name": "Time Clock",
			"link_type": "URL",
			"link_to": "/employee-portal#/roster",
			"icon_name": "calendar",
			"color": "#7c3aed",
			"description": "View weekly staff roster details.",
			"sequence": 730,
			"roles": time_clock_roles,
		},
		{
			"shortcut_name": "Employee Checkins",
			"section_name": "Time Clock",
			"link_type": "DocType",
			"link_to": "Employee Checkin",
			"icon_name": "check",
			"color": "#16a34a",
			"description": "Open employee check-in records.",
			"sequence": 740,
			"roles": ["HR Manager", "System Manager"],
		},
		{
			"shortcut_name": "Attendance Records",
			"section_name": "Time Clock",
			"link_type": "DocType",
			"link_to": "Attendance",
			"icon_name": "file-text",
			"color": "#0284c7",
			"description": "Open finalized attendance records.",
			"sequence": 750,
			"roles": ["HR Manager", "System Manager"],
		},
		{
			"shortcut_name": "Back Up",
			"section_name": "Back Up",
			"link_type": "URL",
			"link_to": "/app/backups",
			"icon_name": "download",
			"color": "#334155",
			"description": "Open Frappe backup management.",
			"sequence": 810,
			"roles": admin_roles,
		},
		{
			"shortcut_name": "Backup Files",
			"section_name": "Back Up",
			"link_type": "DocType",
			"link_to": "File",
			"icon_name": "folder",
			"color": "#475569",
			"description": "Review exported and backup-related files.",
			"sequence": 820,
			"roles": admin_roles,
		},
	]
