/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClockWidget: typeof import('./src/components/ClockWidget.vue')['default']
    ModernCalendar: typeof import('./src/components/ModernCalendar.vue')['default']
    PortalLayout: typeof import('./src/components/PortalLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StandardCalendar: typeof import('./src/components/StandardCalendar.vue')['default']
  }
}
